/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface FichajeEdit { 
    id?: number;
    employeeId?: number;
    initialTime?: string;
    exitTime?: string;
    initialLocation?: string;
    exitLocation?: string;
}

