/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface FichajeFilter { 
    id?: number;
    employeeId?: number;
    initialTimeStart?: string;
    initialTimeEnd?: string;
    exitTimeStart?: string;
    exitTimeEnd?: string;
    initialLocation?: string;
    exitLocation?: string;
}

