/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface OrderFilter { 
    id?: number;
    creationTimeStart?: string;
    creationTimeEnd?: string;
    deliveryTimeStart?: string;
    deliveryTimeEnd?: string;
    clientId?: number;
    orderStatus?: string;
    minAmount?: number;
    maxAmount?: number;
    deliveryAddress?: string;
}

