/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Sortnull } from './sortnull';
import { Pageablenull } from './pageablenull';
import { OrderEdit } from './orderEdit';


export interface PageOrderEdit { 
    totalElements?: number;
    totalPages?: number;
    size?: number;
    content?: Array<OrderEdit>;
    number?: number;
    sort?: Sortnull;
    numberOfElements?: number;
    first?: boolean;
    last?: boolean;
    pageable?: Pageablenull;
    empty?: boolean;
}

