/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserDB } from './userDB';


export interface RolDB { 
    id?: number;
    name?: string;
    description?: string;
    users?: Set<UserDB>;
}

