/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserFilter { 
    id?: number;
    name?: string;
    email?: string;
    enabled?: boolean;
    createdAtStart?: string;
    createdAtEnd?: string;
    lastLoginStart?: string;
    lastLoginEnd?: string;
}

