/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RoleDTO } from './roleDTO';


export interface UserView { 
    id?: number;
    name?: string;
    email?: string;
    enabled?: boolean;
    roles?: Set<RoleDTO>;
}

