/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RolDB } from './rolDB';


export interface UserDB { 
    id?: number;
    roles?: Set<RolDB>;
    name?: string;
    email?: string;
    password?: string;
    enabled?: boolean;
    createdAt?: string;
    updatedAt?: string;
    lastLogin?: string;
    verificationToken?: string;
}

